<a href="https://colab.research.google.com/github/Atrailyus/IT7103/blob/main/Assignment_1_Using_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1

- Loading data
- Manipulating data (i.e. preprocessing), may combine with `scikit-learn`
- Exploring data (some calls it preliminary analysis), may combine with visualization with matplotlib


(Assignment Question 1.)  Below I was able to load the data sets from both employee_rating.csv. Also the data from employee_general csv.

In [80]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/IT7103/employee_rating.csv')
data

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468
...,...,...,...,...,...,...,...,...
1465,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571
1466,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991
1467,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142
1468,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390
1469,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404

Note: it is very important to know the **format of the data file** so we can load it correctly. The file `stroke.csv` is a comma-delimited file in which rows are defined by lines, and fields in each columns are separated by comma `,`.

However, csv format, while common, are not guaranteed. Fields may be separated by other characters, for examples, `|`, so if it is possible, you should **always look at the raw data file first**.

Other information that may be needed include whether the file consists of columns' names or special characters (e.g., from other languages). These will affect the settings of our `read_csv()` function.

For example, the file `stroke_bar.csv` use the `|` instead of `,`. It also does not have column names.

In this case, using the default settings of read_csv, our data will be loaded incorrectly. As you can see below, everything is read into one column. The first row becomes the column's name.

In [81]:
employee_rating = pd.read_csv('/content/drive/MyDrive/IT7103/employee_rating.csv')
employee_rating

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468
...,...,...,...,...,...,...,...,...
1465,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571
1466,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991
1467,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142
1468,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390
1469,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404

If the delimiter is not `,`, we can change the argument `sep=` to the correct character. `header=None` will help fix the issue with files without columns' names

In [82]:
employee_rating = pd.read_csv('/content/drive/MyDrive/IT7103/employee_rating.csv', sep=",", header=None)
employee_rating

,0,1,2,3,4,5,6,7
0,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
1,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
2,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
3,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
4,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
...,...,...,...,...,...,...,...,...
1466,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571
1467,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991
1468,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142
1469,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390
1470,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404

The columns' names are just numbers now, however. We can change that if wished using the `columns` property of the dataframe.

In [83]:
employee_rating.columns = ['EmployeeNumber','Department','EnvironmentSatisfaction','JobRole',
                    'PerformanceRating','YearsAtCompany','YearsInCurrentRole',
                    'MonthlyIncome']
employee_rating

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
0,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
1,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
2,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
3,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
4,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
...,...,...,...,...,...,...,...,...
1466,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571
1467,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991
1468,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142
1469,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390
1470,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404

`stroke_2` and `stroke_3` are just for demonstration purpose. Henceforth, we will only use the original dataframe `data`.

**Self-research note: please read about fixed-width data format and how to import them using pandas**

Another useful information to look at is the data type of each column in the loaded dataframe. We can access this using `dtypes`. Verify that
- Numeric columns are read in as either `float` or `int`
- Class columns should be `object`

If a numeric column is `object`, it may consists of text values in the datafile, in which case we should examine more closely to resolve the issue. This is very important later on since numerical columns and class columns are processed differently.

In [73]:
data.dtypes

EmployeeNumber|Education|EducationField|MaritalStatus    object
dtype: object

This data set is from the employee_general set.  Data type is Object.

#employee_rating.columns = ['EmployeeNumber','Department','EnvironmentSatisfaction','JobRole',
                    'PerformanceRating','YearsAtCompany','YearsInCurrentRole',
                    'MonthlyIncome']
#employee_general

In [84]:
data.dtypes

EmployeeNumber              int64
Department                 object
EnvironmentSatisfaction    object
JobRole                    object
PerformanceRating          object
YearsAtCompany              int64
YearsInCurrentRole          int64
MonthlyIncome               int64
dtype: object

We can use the `head()` method to look at several first rows in a dataframe. `n=` argument specifies the number of rows to display.

In [6]:
data.head(n=10)

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468
5,8,Research & Development,Very High,Laboratory Technician,Excellent,7,7,3068
6,10,Research & Development,High,Laboratory Technician,Outstanding,1,0,2670
7,11,Research & Development,Very High,Laboratory Technician,Outstanding,1,0,2693
8,12,Research & Development,Very High,Manufacturing Director,Outstanding,9,7,9526
9,13,Research & Development,High,Healthcare Representative,Excellent,7,7,5237

# Slicing DataFrame

There are a few ways of slicing a Pandas DataFrame.

Using a **single index system** results in pandas trying to select **columns**. In dataframes that have headers, using numeric index results in error. You have to use the columns' names instead.

In [7]:
data[0]

KeyError: 0

Slicing correctly, the selected column will be **viewed** as a 1D series

In [8]:
data['YearsAtCompany']

0        6
1       10
2        0
3        8
4        2
        ..
1465     5
1466     7
1467     6
1468     9
1469     4
Name: YearsAtCompany, Length: 1470, dtype: int64

We can select multiple columns in a list which result in a dataframe view

In [9]:
data[['PerformanceRating','YearsAtCompany','YearsInCurrentRole']]

     PerformanceRating  YearsAtCompany  YearsInCurrentRole
0            Excellent               6                   4
1          Outstanding              10                   7
2            Excellent               0                   0
3            Excellent               8                   7
4            Excellent               2                   2
...                ...             ...                 ...
1465         Excellent               5                   2
1466         Excellent               7                   7
1467       Outstanding               6                   2
1468         Excellent               9                   6
1469         Excellent               4                   3

[1470 rows x 3 columns]

Row slicing can be added after columns in a <b>different</b> bracket system

In [10]:
data[['PerformanceRating','YearsAtCompany','YearsInCurrentRole']][10:20]

   PerformanceRating  YearsAtCompany  YearsInCurrentRole
10         Excellent               5                   4
11         Excellent               9                   5
12         Excellent               5                   2
13         Excellent               2                   2
14         Excellent               4                   2
15         Excellent              10                   9
16         Excellent               6                   2
17         Excellent               1                   0
18         Excellent              25                   8
19         Excellent               3                   2

To have a slicing syntax that is closer to numpy, we use `DataFrame.loc` or `DataFrame.iloc` to slice DataFrame. You need to provide two slicing conditions, one for row slicing and one for column slicing:

**`DataFrame.loc[{row condition} , {column condition}]`**    <== this is to slice columns using their names

or

**`DataFrame.iloc[{row condition} , {column condition}]`**   <== this is to slice columns using their numeric index

**<i>An important note when slicing a pandas dataframe with `loc` is that the `end_index` will now be included in the result</i>**

In [11]:
data.loc[[10,60,110,200],['Department','EnvironmentSatisfaction','MonthlyIncome']]

                 Department EnvironmentSatisfaction  MonthlyIncome
10   Research & Development                     Low           2426
60   Research & Development                     Low           6162
110  Research & Development                     Low           7484
200  Research & Development                    High           4298

In [12]:
data.loc[:30:3,['Department','EnvironmentSatisfaction','MonthlyIncome']]

                Department EnvironmentSatisfaction  MonthlyIncome
0                    Sales                  Medium           5993
3   Research & Development               Very High           2909
6   Research & Development                    High           2670
9   Research & Development                    High           5237
12  Research & Development                     Low           2911
15  Research & Development                  Medium           9980
18                   Sales                     Low          15427
21                   Sales                    High           3407
24  Research & Development                  Medium           2960
27                   Sales                    High           6825
30  Research & Development                    High           2496

In [13]:
data.loc[60:100:4,'YearsAtCompany':'YearsInCurrentRole']

     YearsAtCompany  YearsInCurrentRole
60                9                   8
64               17                  14
68                3                   2
72                1                   1
76               15                  13
80               10                   8
84                5                   2
88               11                  10
92               11                   8
96                3                   2
100               3                   2

`iloc` will give a slicing scheme that is identical to `numpy`

In [14]:
#to use column indices instead of their names, we use iloc
data.iloc[[10,40,70,210,1004], [1,3,5,7]]

,Department,JobRole,YearsAtCompany,MonthlyIncome
10,Research & Development,Laboratory Technician,5,2426
40,Research & Development,Laboratory Technician,1,1951
70,Sales,Sales Executive,4,5473
210,Sales,Sales Executive,14,10400
1004,Research & Development,Laboratory Technician,7,3578

Being identical to numpy, the end_index will **not** be included. This is very important to remember, since incorrect index may lead to the target being included in the feature set which make any models meaningless.

To be certain, **always print** the slicing result so you can verify it is as you expect.

In [63]:
data.iloc[:10, 4:-1]

  PerformanceRating  YearsAtCompany  YearsInCurrentRole
0         Excellent               6                   4
1       Outstanding              10                   7
2         Excellent               0                   0
3         Excellent               8                   7
4         Excellent               2                   2
5         Excellent               7                   7
6       Outstanding               1                   0
7       Outstanding               1                   0
8       Outstanding               9                   7
9         Excellent               7                   7

Similar to a numpy array, we can slice a dataframe using conditions with both with loc and iloc. You have to make sure the columns are in their correct data types to avoid unexpected results or errors. For examples, compare an object column to a number may cause weird behaviours.

In [15]:
data.loc[data['YearsAtCompany']<=30,:]

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468
...,...,...,...,...,...,...,...,...
1465,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571
1466,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991
1467,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142
1468,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390
1469,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404

In [16]:
data.loc[data['EnvironmentSatisfaction']=='Very High',:]

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
5,8,Research & Development,Very High,Laboratory Technician,Excellent,7,7,3068
7,11,Research & Development,Very High,Laboratory Technician,Outstanding,1,0,2693
8,12,Research & Development,Very High,Manufacturing Director,Outstanding,9,7,9526
...,...,...,...,...,...,...,...,...
1460,2054,Research & Development,Very High,Research Scientist,Excellent,5,4,3785
1461,2055,Sales,Very High,Sales Executive,Excellent,3,2,10854
1464,2060,Sales,Very High,Sales Representative,Excellent,4,2,2966
1466,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991
1468,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390

we can combine conditions, `&` for **and**, and `|` for **or**. Remember to wrap each condition in parentheses **()**

In [17]:
data.loc[(data['YearsAtCompany']==10) & (data['MonthlyIncome']<=5100),:]

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
26,33,Research & Development,Medium,Research Scientist,Outstanding,10,2,3919
32,41,Research & Development,Very High,Laboratory Technician,Excellent,10,0,2206
61,79,Research & Development,Very High,Laboratory Technician,Excellent,10,3,2406
120,159,Research & Development,Low,Research Scientist,Outstanding,10,7,2613
155,208,Research & Development,Very High,Manufacturing Director,Excellent,10,7,4319
282,388,Sales,Medium,Sales Executive,Excellent,10,7,4554
334,452,Research & Development,Very High,Research Scientist,Excellent,10,9,3697
404,536,Research & Development,High,Laboratory Technician,Excellent,10,0,4558
412,550,Research & Development,High,Manufacturing Director,Excellent,10,7,4810
488,659,Research & Development,High,Healthcare Representative,Excellent,10,2,4089
503,683,Research & Development,Medium,Research Scientist,Excellent,10,9,2691
514,702,Research & Development,Low,Research Scientist,Excellent,10,8,3348
519,710,Research & Development,Medium,Research Scientist,Excellent,10,7,2720
562,780,Research & Development,Very High,Research Scientist,Excellent,10,9,2686
594,824,Research & Development,High,Research Scientist,Outstanding,10,7,2700
636,881,Research & Development,Very High,Research Scientist,Excellent,10,2,2022
676,942,Research & Development,Very High,Healthcare Representative,Outstanding,10,6,4014
779,1081,Research & Development,Low,Research Scientist,Excellent,10,0,2461
783,1085,Research & Development,Medium,Research Scientist,Excellent,10,6,3376
825,1150,Research & Development,Medium,Manufacturing Director,Excellent,10,7,5056
852,1192,Research & Development,Medium,Laboratory Technician,Excellent,10,8,3131
872,1220,Sales,Medium,Sales Executive,Excellent,10,7,4539
874,1224,Research & Development,High,Laboratory Technician,Excellent,10,7,3491
891,1246,Research & Development,Low,Research Scientist,Excellent,10,5,2011
923,1289,Human Resources,High,Human Resources,Excellent,10,9,4490
939,1309,Research & Development,Very High,Laboratory Technician,Excellent,10,4,4883
1089,1543,Research & Development,Low,Research Scientist,Excellent,10,8,4285
1122,1586,Research & Development,Medium,Laboratory Technician,Excellent,10,9,4723
1130,1596,Research & Development,Medium,Laboratory Technician,Excellent,10,9,3407
1143,1612,Sales,Low,Sales Executive,Excellent,10,7,4385
1155,1627,Research & Development,High,Laboratory Technician,Excellent,10,8,3069
1188,1669,Sales,Low,Sales Executive,Excellent,10,0,4187
1212,1701,Research & Development,Medium,Research Scientist,Excellent,10,9,2929
1233,1729,Research & Development,Medium,Research Scientist,Excellent,10,0,2862
1280,1794,Human Resources,High,Human Resources,Excellent,10,0,4071
1282,1798,Research & Development,Very High,Research Scientist,Excellent,10,8,3143
1291,1809,Research & Development,Very High,Manufacturing Director,Excellent,10,3,4213
1341,1881,Research & Development,Medium,Laboratory Technician,Excellent,10,8,4197
1347,1890,Human Resources,Medium,Human Resources,Outstanding,10,1,3886
1389,1956,Research & Development,Very High,Research Scientist,Outstanding,10,8,5003
1424,2008,Research & Development,Medium,Research Scientist,Excellent,10,7,5098
1444,2032,Research & Development,Very High,Laboratory Technician,Excellent,10,9,2339

Note that slicing with `loc()` or `iloc()` give a view of the DataFrame.

We can make a copy if the particular subset is important to use later on.

In [18]:
data_young_urban = data.loc[(data['EnvironmentSatisfaction']=='High') & (data['YearsInCurrentRole']<=7), :]
data_young_urban

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
6,10,Research & Development,High,Laboratory Technician,Outstanding,1,0,2670
9,13,Research & Development,High,Healthcare Representative,Excellent,7,7,5237
14,19,Research & Development,High,Laboratory Technician,Excellent,4,2,2028
21,27,Sales,High,Sales Representative,Outstanding,5,3,3407
...,...,...,...,...,...,...,...,...
1455,2048,Research & Development,High,Research Scientist,Excellent,2,2,2809
1456,2049,Research & Development,High,Healthcare Representative,Excellent,10,2,5689
1457,2051,Research & Development,High,Research Scientist,Excellent,5,3,2001
1458,2052,Research & Development,High,Research Scientist,Excellent,4,3,2977
1465,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571

# Feature Processing

Similar to numpy, we can apply mathematical operations or functions on numeric columns in a dataframe. Math functions can be imported from `numpy`.

In [19]:
import numpy as np

np.log(data['MonthlyIncome'])

0       8.698347
1       8.542861
2       7.644919
3       7.975565
4       8.151333
          ...
1465    7.852050
1466    9.209440
1467    8.722906
1468    8.592301
1469    8.390268
Name: MonthlyIncome, Length: 1470, dtype: float64

We can directly assign the values to a new column name

In [20]:
data['log_income'] = np.log(data['MonthlyIncome'])
data

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome,log_income
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993,8.698347
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130,8.542861
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090,7.644919
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909,7.975565
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468,8.151333
...,...,...,...,...,...,...,...,...,...
1465,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571,7.852050
1466,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991,9.209440
1467,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142,8.722906
1468,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390,8.592301
1469,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404,8.390268

(Assignment Question 2.) Here I was able to create a new column.

## Binning Numeric Columns

Occasionally, the original values of a numeric column could be noisy which hurts a model's performance. That can sometimes be solved by **binning the column**. Examples are ages into age groups, incomes into income groups, and so on.

In this data, we can try binning `age`. First, I will reload the data to reset all changes.

In [26]:
data = pd.read_csv('/content/drive/MyDrive/IT7103/employee_rating.csv')
data.head()

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468

In [85]:
data = pd.read_csv('/content/drive/MyDrive/IT7103/employee_general.csv')
data.head()

  EmployeeNumber|Education|EducationField|MaritalStatus
0                     1|College|Life Sciences|Single
1              2|Below College|Life Sciences|Married
2                             4|College|Other|Single
3                     5|Master|Life Sciences|Married
4                    7|Below College|Medical|Married

Then, we can use the `pandas.cut()` function to bin the column. This function takes two inputs:
- a list of split values. Each bin is formed from two consecutive splits in this list.
- a list of bin names. Should have one item less than the split list.

In [27]:
bins = [0, 5, 60, np.inf] #the range are 0<age<=30, 30<age<=60, and 60<age
names = [1, 2, 3]          #age 0-30 will be bin 1, 30-60 bin 2, and over 60 bin 3

data['LessYears'] = pd.cut(data['YearsAtCompany'], bins=bins, labels=names)
data

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome,LessYears
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993,2
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130,2
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090,NaN
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909,2
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468,1
...,...,...,...,...,...,...,...,...,...
1465,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571,1
1466,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991,2
1467,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142,2
1468,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390,2
1469,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404,1

Note that, categorizing a column should base on some justifications. For example, age groups into youth, middle age, elderly, or bmi into underweight, normal, and overweight. Arbitrary categories may be more harmful than helpful for a model.

## Convert Ordinal Categories to Numbers

It is also quite often we want to convert categories into numbers. However, you have to make sure the order in the numerical values makes sense.

For example, categories like `low`, `medium`, `high` can be converted to 1, 2, 3 because 1 < 2 is equivalent `low` < `medium` which is meaningful.

However, categories like `Europe`, `Asia`, `Africa`... do not have any inherent order. If you convert them to 1, 2, 3, does 1 < 2, or `Europe` < `Asia` make sense? These types of data need a different treatment discussed in module 5.

In this example, we will convert three groups of `smoking_status` into 1, 2, 3 as follows

- never smoked ==> 1
- formerly smoked ==> 2
- smokes ==> 3

Note that this conversion does not necessarily make senses, we are just using this column as an example. We will use `pandas.map()`.

`pandas.map()` takes input as a **dictionary** where each key-value pair representating the transformation of one category to one new value.

In [28]:
Environment_map = {
    'High':1,
    'Medium':2,
    'Low':3
}
data['EnvironmentLevel'] = data['EnvironmentSatisfaction'].map(Environment_map)
data

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome,LessYears,EnvironmentLevel
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993,2,2.0
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130,2,1.0
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090,NaN,NaN
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909,2,NaN
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468,1,3.0
...,...,...,...,...,...,...,...,...,...,...
1465,2061,Research & Development,High,Laboratory Technician,Excellent,5,2,2571,1,1.0
1466,2062,Research & Development,Very High,Healthcare Representative,Excellent,7,7,9991,2,NaN
1467,2064,Research & Development,Medium,Manufacturing Director,Outstanding,6,2,6142,2,2.0
1468,2065,Sales,Very High,Sales Executive,Excellent,9,6,5390,2,NaN
1469,2068,Research & Development,Medium,Laboratory Technician,Excellent,4,3,4404,1,2.0

(Assignment Question 3.) In the above code, the employee_rating data was uploaded.  I did the 1,2,3 concept using the Environment Tab.  The new colomn was created showing the results.

In [86]:
Married_map = {
    'Married':1,
    'Single':2,
    'Divorced':3
}
data['HowsMarrige'] = data['MaritalStatus'].map(Married_map)
data

KeyError: 'MaritalStatus'

(Assigment Question 4.) The above data us from the employee_general data.  Here I am using the marital status data in to set up the 1,2,3.  At the time, I keep on getting this error, as if the program can't see my Tab.

### Check Unique Values in a Class Column

Sometimes the data description may not include a list of unique values for the class columns. We can simply use pandas to do that instead with the `unique()` method. This method can be called from a column.

In [34]:
data['ever_married'].unique()

KeyError: 'ever_married'

In [ ]:
data['Residence_type'].unique()

array(['Urban', 'Rural'], dtype=object)

In [ ]:
data['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

# Merging Data

Projects in which data comes from multiple sources are fairly common. In such cases, we need to merge them into a single dataset for modeling. Merging is usually done using an ID attribute.

For example, suppose the stroke data is not originally provided as a single file but two, demography and medical history

(Assigment Question 5.)  For the Merging, I was able to upload the data sets, and I did do one merge, for some reason the second set was not able to see the data set, (EmployeeNumber) to be able to merge with one another.  The merging did run.

In [62]:
employee = pd.read_csv('/content/drive/MyDrive/IT7103/employee_rating.csv')
employee.head()

,EmployeeNumber,Department,EnvironmentSatisfaction,JobRole,PerformanceRating,YearsAtCompany,YearsInCurrentRole,MonthlyIncome
0,1,Sales,Medium,Sales Executive,Excellent,6,4,5993
1,2,Research & Development,High,Research Scientist,Outstanding,10,7,5130
2,4,Research & Development,Very High,Laboratory Technician,Excellent,0,0,2090
3,5,Research & Development,Very High,Research Scientist,Excellent,8,7,2909
4,7,Research & Development,Low,Laboratory Technician,Excellent,2,2,3468

In [63]:
employeegen = pd.read_csv('/content/drive/MyDrive/IT7103/employee_general.csv')
employeegen.head()

  EmployeeNumber|Education|EducationField|MaritalStatus
0                     1|College|Life Sciences|Single
1              2|Below College|Life Sciences|Married
2                             4|College|Other|Single
3                     5|Master|Life Sciences|Married
4                    7|Below College|Medical|Married

To train a `scikit-learn` model using both data source, we need to merge these two into one. Notice that both come with subject_id that indicates whether a row from the two sets refer to the same subject. We can use this attribute to merge.

Merging is fairly simple with the merge method. We can call merge from either dataframe, the argument would be the other dataframe, and the attribute to be used to match rows in the two dataframes.

In [64]:
display('employee', 'employeegen', "pd.merge(employee, employeegen, on='EmployeeNumber')")

'employee'

'employeegen'

"pd.merge(employee, employeegen, on='EmployeeNumber')"

In [66]:
employee.merge(employeegen, on='EmployeeNumber')

KeyError: 'EmployeeNumber'

There are multiple types of merging. If all  instances in either dataframe have matched IDs on the other, different types of merging give the same result. Otherwise, we need to understand our needs before merging to select the correct type.

For example, we want to merge two small dataframe as follows, but some rows do not have IDs in both sides

In [ ]:
demo_s = pd.read_csv('/content/drive/MyDrive/IT7103/demography_small.csv')
demo_s

   subject_id  gender ever_married      work_type Residence_type
0       10001    Male          Yes        Private          Urban
1       10003  Female          Yes        Private          Urban
2       10004  Female          Yes  Self-employed          Rural
3       10006    Male          Yes        Private          Rural
4       10007  Female           No        Private          Urban
5       10008  Female          Yes        Private          Urban

In [ ]:
med_s = pd.read_csv('/content/drive/MyDrive/IT7103/medical_history_small.csv')
med_s

   subject_id  hypertension  heart_disease  avg_glucose_level   bmi  stroke
0       10001             0              1             228.69  36.6       1
1       10003             0              0             171.23  34.4       1
2       10004             1              0             174.12  24.0       1
3       10005             0              0             186.21  29.0       1
4       10006             1              1              70.09  27.4       1
5       10009             1              0              80.43  29.7       1

When calling `merge()`, the dataframe from which `merge()` is called is the **left** dataframe, and the one used as argument is the **right** dataframe.

For example,

`demo.merge(medhis, on='subject_id')`

means `demo` is the left dataframe, and `medhis` is the right dataframe. On the other hand,

`medhis.merge(demo, on='subject_id')`

means `medhis` is the left dataframe, and `demo` is the right one.

A **left-merge** keep all the rows in the left dataframe, and only rows in the right dataframe that have matched ID from the left. Rows from the left without matched IDs in the right have all their right columns become missing (NaN)

In [ ]:
demo_s.merge(med_s, on='subject_id', how='left')

,subject_id,gender,ever_married,work_type,Residence_type,hypertension,heart_disease,avg_glucose_level,bmi,stroke
0,10001,Male,Yes,Private,Urban,0.0,1.0,228.69,36.6,1.0
1,10003,Female,Yes,Private,Urban,0.0,0.0,171.23,34.4,1.0
2,10004,Female,Yes,Self-employed,Rural,1.0,0.0,174.12,24.0,1.0
3,10006,Male,Yes,Private,Rural,1.0,1.0,70.09,27.4,1.0
4,10007,Female,No,Private,Urban,NaN,NaN,NaN,NaN,NaN
5,10008,Female,Yes,Private,Urban,NaN,NaN,NaN,NaN,NaN

A **right-merge** keep all the rows in the right dataframe, and only rows in the left dataframe that have matched ID from the right. Rows from the right without matched IDs in the right have all their left columns become missing (NaN)

In [ ]:
demo_s.merge(med_s, on='subject_id', how='right')

,subject_id,gender,ever_married,work_type,Residence_type,hypertension,heart_disease,avg_glucose_level,bmi,stroke
0,10001,Male,Yes,Private,Urban,0,1,228.69,36.6,1
1,10003,Female,Yes,Private,Urban,0,0,171.23,34.4,1
2,10004,Female,Yes,Self-employed,Rural,1,0,174.12,24.0,1
3,10005,NaN,NaN,NaN,NaN,0,0,186.21,29.0,1
4,10006,Male,Yes,Private,Rural,1,1,70.09,27.4,1
5,10009,NaN,NaN,NaN,NaN,1,0,80.43,29.7,1

An **outer-merge** keeps all rows. Rows without matched from either sides will have those sections as missing

In [ ]:
demo_s.merge(med_s, on='subject_id', how='outer')

,subject_id,gender,ever_married,work_type,Residence_type,hypertension,heart_disease,avg_glucose_level,bmi,stroke
0,10001,Male,Yes,Private,Urban,0.0,1.0,228.69,36.6,1.0
1,10003,Female,Yes,Private,Urban,0.0,0.0,171.23,34.4,1.0
2,10004,Female,Yes,Self-employed,Rural,1.0,0.0,174.12,24.0,1.0
3,10005,NaN,NaN,NaN,NaN,0.0,0.0,186.21,29.0,1.0
4,10006,Male,Yes,Private,Rural,1.0,1.0,70.09,27.4,1.0
5,10007,Female,No,Private,Urban,NaN,NaN,NaN,NaN,NaN
6,10008,Female,Yes,Private,Urban,NaN,NaN,NaN,NaN,NaN
7,10009,NaN,NaN,NaN,NaN,1.0,0.0,80.43,29.7,1.0

An **inner-merge** only keeps rows with matched IDs from both sides. All rows without matches are dropped.

In [ ]:
demo_s.merge(med_s, on='subject_id', how='inner')

,subject_id,gender,ever_married,work_type,Residence_type,hypertension,heart_disease,avg_glucose_level,bmi,stroke
0,10001,Male,Yes,Private,Urban,0,1,228.69,36.6,1
1,10003,Female,Yes,Private,Urban,0,0,171.23,34.4,1
2,10004,Female,Yes,Self-employed,Rural,1,0,174.12,24.0,1
3,10006,Male,Yes,Private,Rural,1,1,70.09,27.4,1